- id: '1607889775235'
  alias: Go to bed
  description: Licht in Bad gr. und Schlafzimmer einschalten
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.keyfob
      scene_id: 5
      scene_data: 7800
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: go_to_bed
  condition:
  - condition: time
    after: '19:00:00'
  action:
  - type: turn_on
    device_id: 105af14733b7e3f6878b3302e4ba5aca
    entity_id: light.badezimmer_gr_dimmer_1_level
    domain: light
    brightness_pct: 15
  - type: turn_on
    device_id: 6f789b5aaaa5db36923bab77068235e3
    entity_id: light.nachtischlicht_wendelin
    domain: light
    brightness_pct: 50
  mode: single
- id: '1607944968245'
  alias: Motion Technikraum
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 9c0c318b8047fb24403e56c6ecbca801
    entity_id: binary_sensor.presence_28
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: 9c0c318b8047fb24403e56c6ecbca801
    entity_id: binary_sensor.presence_28
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - type: is_motion
        condition: device
        device_id: 9c0c318b8047fb24403e56c6ecbca801
        entity_id: binary_sensor.presence_28
        domain: binary_sensor
      sequence:
      - type: turn_on
        device_id: 6036b3336cf042dc9fe4120887474b74
        entity_id: switch.switch_technikraum_switch
        domain: switch
    - conditions:
      - type: is_no_motion
        condition: device
        device_id: 9c0c318b8047fb24403e56c6ecbca801
        entity_id: binary_sensor.presence_28
        domain: binary_sensor
      sequence:
      - type: turn_off
        device_id: 6036b3336cf042dc9fe4120887474b74
        entity_id: switch.switch_technikraum_switch
        domain: switch
    default: []
  mode: single
- id: '1608990055556'
  alias: Ganglicht
  description: Ganglicht an/aus je nachdem ob Bewegung oder der Schalter betätigt
    wurde
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_gang
  - platform: state
    entity_id: switch.gang_zwave_switch
  - platform: state
    entity_id: input_boolean.gang_licht_bewegungsmelder
  - platform: state
    entity_id: input_number.gang_motion_brightness
  - platform: state
    entity_id: input_number.gang_motion_brightness_lux_limit
  - platform: homeassistant
    event: start
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.gang_zwave_switch
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
        entity_id: light.ganglicht
    default:
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.gang_licht_bewegungsmelder
          state: 'on'
        - condition: state
          entity_id: binary_sensor.motion_gang
          state: 'on'
        - condition: template
          value_template: "{% if ( states( 'sensor.eingang_luminance' ) | float) <\n\
            \    ( states( 'input_number.gang_motion_brightness_lux_limit' ) | float\
            \ ) %}true\n    {% endif %}"
        sequence:
        - service: light.turn_on
          data:
            brightness_pct: '{{ states(''input_number.gang_motion_brightness'') |
              int }}'
          entity_id: light.ganglicht
      default:
      - service: light.turn_off
        data: {}
        entity_id: light.ganglicht
  mode: restart
- id: '1608990595838'
  alias: Ganglicht mit Bewegung trigger
  description: Schaltet die Ganglicht Bewegungsmelder an/aus
  trigger:
  - platform: time
    at: 06:00:00
  - device_id: c079c6175f0a4f26920ab30ec711c375
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      node_id: 33
      scene_id: 4
      scene_data: 1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: 06:00:00
        before: 06:01:00
      sequence:
      - service: input_boolean.turn_on
        data: {}
        entity_id: input_boolean.gang_licht_bewegungsmelder
    default:
    - service: input_boolean.toggle
      data: {}
      entity_id: input_boolean.gang_licht_bewegungsmelder
  mode: restart
- id: '1608990846676'
  alias: Ganglicht von externen Tastern
  description: Ganglicht zu 100% ein von externen Tastern im Gang
  trigger:
  - platform: device
    type: turned_on
    device_id: 573c11bd695edb7e46c7a2acee4d2835
    entity_id: switch.gang_helper_spiegel
    domain: switch
  - platform: device
    type: turned_on
    device_id: 5d3fcf20370a4f9aa9490e203cdc2a05
    entity_id: switch.gang_helper_garderobe
    domain: switch
  - device_id: c079c6175f0a4f26920ab30ec711c375
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 972dd1ae14e64277a125e7f027cf7096
    entity_id: switch.gang_zwave_switch
    domain: switch
  - type: turn_off
    device_id: 573c11bd695edb7e46c7a2acee4d2835
    entity_id: switch.gang_helper_spiegel
    domain: switch
  - type: turn_off
    device_id: 5d3fcf20370a4f9aa9490e203cdc2a05
    entity_id: switch.gang_helper_garderobe
    domain: switch
  mode: restart
- id: '1610102746283'
  alias: Wendelin Contacts Birthday notification
  description: When someone in Wendelin's contact list has birthday, he will get a
    notification on his Phone
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: calendar.geburtstage_von_kontakten_geburtstage_von_kontakten
    state: 'on'
  action:
  - device_id: e8a0fff1e51d4db39c2f927ed4714e4a
    domain: mobile_app
    type: notify
    message: Heute hat {{state_attr('calendar.geburtstage_von_kontakten_geburtstage_von_kontakten',
      'message')}} Geburtstag!
  mode: single
