- platform: template
  sensors:
    motion_gang:
      friendly_name: 'Bewegung im Gang'
      value_template: >-
        {{ is_state('binary_sensor.xiaomi_motion_1', 'on')
            or is_state('binary_sensor.multisensor_gang_motion', 'on')
            or is_state('binary_sensor.xiaomi_motion_2', 'on')
            or is_state('binary_sensor.xiaomi_motion_3', 'on')
            or is_state('binary_sensor.xiaomi_motion_4', 'on') }}