
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
script: !include scripts.yaml

recorder:

speedtestdotnet:

# import files
telegram_bot: !include telegram_bot.yaml
notify: !include notify.yaml
binary_sensor: !include binary_sensor.yaml

# import folders
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
alert: !include_dir_merge_named alerts/

calendar: !include calendar.yaml

sensor: !include sensors.yaml
light: !include light.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
rest_command: !include rest_command.yaml

neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    cover.schlafzimmer:
      invert_percent: true
      invert_openclose_buttons: true
    cover.gaestezimmer:
      invert_percent: true
      invert_openclose_buttons: true
    cover.kinderzimmer:
      invert_percent: true
      invert_openclose_buttons: true
    cover.wohnzimmer_fenster:
      invert_percent: true
      invert_openclose_buttons: true

camera:
  - platform: mjpeg
    still_image_url: !secret camera_snapshot_url
    mjpeg_url: !secret camera_video_url
    verify_ssl: false
    name: Fahrradkamera