- platform: sql
  queries:
    - name: max temp aussen heute
      query: "SELECT MAX(ROUND(state, 1)) AS state FROM states WHERE entity_id = 'sensor.temperature_24' AND created >= strftime('%Y-%m-%d 00:00:00.000000', 'now') AND state != 'unavailable';"
      column: 'state'
      unit_of_measurement: '°C'
- platform: sql
  queries:
    - name: min temp aussen heute
      query: "SELECT MIN(ROUND(state, 1)) AS state FROM states WHERE entity_id = 'sensor.temperature_24' AND created >= strftime('%Y-%m-%d 00:00:00.000000', 'now') AND state != 'unavailable';"
      column: 'state'
      unit_of_measurement: '°C'
- platform: rest
  name: temperatur_aussen_rest
  resource: http://192.168.0.6/data/info.php
  value_template: '{{ value_json.out }}'
  device_class: temperature
  unit_of_measurement: '°C'
- platform: min_max
  type: min
  name: temperatur_aussen
  entity_ids:
    - sensor.temperature_24
    - sensor.temperatur_aussen_rest