- alias: turn_tv_on_and_swith_channel_fire_tv
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_fire_tv
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'off'
  action:
    - service: script.turn_tv_on
    - delay:
      seconds: 12
    - service: script.turn_tv_channel_on_fire_tv

- alias: switch_tv_channel_fire_tv_off
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_orf1
    from: 'on'
    to: 'off'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'on'
  action:
    - service: script.turn_tv_to_hdmi1_and_off

- alias: swith_tv_channel_fire_tv_hdmi1
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_fire_tv
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'on'
  - condition: state
    entity_id: input_select.tv_source
    state: 'HDMI 1'
  action:
    - service: script.turn_tv_channel_on_fire_tv
