- alias: turn_tv_on_and_swith_channel_fire_tv
  trigger:
    - platform: state
      entity_id: input_boolean.tv_channel_fire_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.tv
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.fernseher
    - delay:
        seconds: 15
    - service: script.turn_tv_channel_on_fire_tv

- alias: swith_tv_channel_fire_tv_hdmi1
  trigger:
    - platform: state
      entity_id: input_boolean.tv_channel_fire_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.tv
      state: 'on'
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 1'
  action:
    - service: script.turn_tv_channel_on_fire_tv
