- alias: turn_tv_on_and_swith_channel_orf1
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_orf1
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'off'
  action:
    - service: script.turn_tv_on
    - delay:
      seconds: 12
    - service: script.turn_tv_channel_on_orf1
    - service: script.send_tv_simpli_tv_ok

- alias: switch_tv_channel_orf1_off
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_orf1
    from: 'on'
    to: 'off'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'on'
  action:
    - service: script.turn_tv_off

- alias: swith_tv_channel_orf1_hdmi1
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_orf1
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'on'
  - condition: state
    entity_id: input_select.tv_source
    state: 'HDMI 1'
  action:
    - service: script.turn_tv_channel_on_orf1

- alias: swith_tv_channel_orf1_hdmi2
  trigger:
    platform: state
    entity_id: input_boolean.tv_channel_orf1
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.tv
    state: 'on'
  - condition: state
    entity_id: input_select.tv_source
    state: 'HDMI 2'
  action:
    - service: script.turn_tv_channel_on_orf1
    - service: script.turn_tv_source_left
