- alias: turn_tv_on_and_swith_channel_orf_2
  trigger:
    - platform: state
      entity_id: input_boolean.tv_channel_orf_2
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.tv
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.fernseher
    - delay:
        seconds: 12
    - service: script.turn_tv_channel_on_orf_2

- alias: swith_tv_channel_orf_2_hdmi1
  trigger:
    - platform: state
      entity_id: input_boolean.tv_channel_orf_2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.tv_lock
        state: 'off'
      - condition: state
        entity_id: input_boolean.tv
        state: 'on'
      - condition: state
        entity_id: input_select.tv_source
        state: 'HDMI 1'
  action:
    - service: script.turn_tv_channel_on_orf_2

- alias: swith_tv_channel_orf_2_hdmi2
  trigger:
    - platform: state
      entity_id: input_boolean.tv_channel_orf_2
      to: 'on'
  condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.tv_lock
        state: 'off'
      - condition: state
        entity_id: input_boolean.tv
        state: 'on'
      - condition: state
        entity_id: input_select.tv_source
        state: 'HDMI 2'
  action:
    - service: script.turn_tv_source_left
    - service: script.turn_tv_channel_on_orf_2
