- alias: "Motioneye - Fahrradkamera - Motion started"
  trigger:
    platform: webhook
    webhook_id: motioneye-fahrradkamera-started
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.fahrradkamera_motion_detected
- alias: "Motioneye - Fahrradkamera - Motion ended"
  trigger:
    platform: webhook
    webhook_id: motioneye-fahrradkamera-ended
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.fahrradkamera_motion_detected