- alias: Fernseher switch toggle
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 1001
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 2
        scene_data: 7800
  action:
    - service: switch.toggle
      data:
        entity_id: switch.steckdose_fernseher
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret hdmi_switcher_power
          - !secret simpli_tv_on_off
    - delay:
        seconds: 1
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command: !secret hdmi_switcher_1
    - service: rest_command.phoniebox_stop

- alias: Fernseher vol up
  mode: queued
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 6
        scene_data: 7680
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret soundbar_volume_up


- alias: Fernseher vol down
  mode: queued
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 5
        scene_data: 7680
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret soundbar_volume_down


- alias: switch to TV hdmi
  mode: queued
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 3
        scene_data: 7800
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret hdmi_switcher_1

- alias: switch to Chromecast hdmi
  mode: queued
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 4
        scene_data: 7800
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret hdmi_switcher_2

- alias: Fernseher chromecast pause
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 1002
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 2
        scene_data: 7680
  action:
    - service: media_player.media_play_pause
      data:
        entity_id: media_player.wood_cast

- alias: TV channel up
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 4
        scene_data: 7680
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret simpli_tv_channel_up
- alias: TV channel down
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 3
        scene_data: 7680
  action:
    - service: remote.send_command
      data:
        entity_id: remote.broadlink_rm_mini_remote
        command:
          - !secret simpli_tv_channel_down

- alias: Wohnzimmer stimmung scene TV
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        node_id: 33
        scene_id: 3
        scene_data: 0
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 1004
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.keyfob
        scene_id: 1
        scene_data: 7800
  action:
    - service: light.turn_off
      data:
        entity_id: light.dimmer_wohnzimmer_esstisch
    - service: light.turn_off
      data:
        entity_id: light.dimmer_wohnzimmer_oben
    - service: light.turn_on
      data:
        entity_id: light.dimmer_livingroom_north
        brightness_pct: 40
    - service: light.turn_on
      data:
        entity_id: light.dimmer_wohnzimmer_stimmung_sued
        brightness_pct: 40
    - service: switch.turn_on
      data:
        entity_id: switch.xiaomi_smart_plug
    - service: switch.turn_on
      data:
        entity_id: switch.wohnzimmer_wandleuchten_switch
