- alias: Ganglicht 10% bei Bewegung
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_gang
      from: 'off'
      to: 'on'
  condition:
    # gang licht is not turned on 100%
    - condition: state
      entity_id: switch.gang_zwave_switch
      state: 'off'
    # and outside it is getting dark
    - condition: numeric_state
      entity_id: sensor.eingang_luminance
      below: 100
  action:
    - service: light.turn_on
      data:
        entity_id: light.ganglicht
        brightness_pct: 10

- alias: Ganglicht aus bei keiner Bewegung
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_gang
      from: 'on'
      to: 'off'
  condition:
    # gang licht is not turned on 100%
    - condition: state
      entity_id: switch.gang_zwave_switch
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.ganglicht

- alias: Ganglicht Bewegungsautomation deaktiveren
  trigger:
    - platform: state
      entity_id: automation.ganglicht_10_bei_bewegung
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.gang_zwave_switch
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.ganglicht

- alias: Ganglicht Bewegungsautomation aktivieren
  trigger:
    - platform: state
      entity_id: automation.ganglicht_10_bei_bewegung
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.gang_zwave_switch
      state: 'off'
    - condition: state
      entity_id: binary_sensor.motion_gang
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.eingang_luminance
      below: 100
  action:
    - service: light.turn_on
      data:
        entity_id: light.ganglicht
        brightness_pct: 10

- alias: Ganglicht automation toggle
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 1001
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        node_id: 33
        scene_id: 4
        scene_data: 1
  action:
    - service: automation.toggle
      entity_id: automation.ganglicht_10_bei_bewegung

- alias: Ganglicht automation activate in the morning
  trigger:
    platform: sun
    event: sunset
  action:
    - service: automation.turn_on
      entity_id: automation.ganglicht_10_bei_bewegung