- alias: Ganglicht toggle via taster
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 1002
    - platform: state
      entity_id: switch.gang_garderobe
      from: 'off'
      to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.gang_zwave_switch

- alias: Ganglicht an 100%
  trigger:
    platform: state
    entity_id: switch.gang_zwave_switch
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.ganglicht
        brightness_pct: 100

- alias: Ganglicht aus
  id: 172b17ad-661b-46bf-a5f0-85bab36583ee
  description: 'Ganglicht aus'
  trigger:
    - platform: state
      entity_id: switch.gang_zwave_switch
      from: 'on'
      to: 'off'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.motion_gang
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.eingang_luminance
          below: 100
        - condition: state
          entity_id: automation.ganglicht_10_bei_bewegung
          state: 'on'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.ganglicht
              brightness_pct: 10
      default:
        - service: light.turn_off
          data:
            entity_id: light.ganglicht
