- alias: Tor öffnen vom Handy
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: open_tor
  action:
    - service: switch.turn_on
      entity_id: switch.open_door_switch