- alias: tor klingel
  trigger:
    - platform: state
      entity_id: switch.door_bell_switch_sensor
      from: 'off'
      to: 'on'
  action:
    - service: telegram_bot.send_sticker
      data:
        file: CAACAgIAAxkBAAIHyF-2u5KaCfd28UVLYV8loQL349rkAAJMAAOvxlEaOt_FkTwsoz8eBA
        target: !secret telegram_chat_tor_channel
    - service: telegram_bot.send_message
      data:
        message: '*🔔 Ring - Torklingel*'
        target: !secret telegram_chat_tor_channel
        inline_keyboard: [[["Tor öffnen", "/open"]]]
- alias: tor open via telegram
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/open'
  action:
    - service: switch.turn_on
      entity_id: switch.open_door_switch
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Tor wird für 3 Sekunden geöffnet'
        show_alert: true
