- alias: start door bot for guest
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start@ki_adi_mundi_bot'
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret telegram_chat_tor_guest_group
        message: 'Willkommen! Um das Tor zu öffnen klicke einfach auf "Tor öffnen" und das Tor wird 3 Sekunden lang geöffnet. Viel Spaß!'
        inline_keyboard: [[["Tor öffnen", "/open"]]]
