- alias: alle runter um 9
  trigger:
    platform: time
    at: input_datetime.raffstores_down
  action:
    - service: script.turn_on
      entity_id: script.raffstores_down

- alias: alle up ausser schlafzimmer rauf um 1630
  trigger:
    platform: time
    at: input_datetime.raffstores_up_1
  action:
    - service: script.turn_on
      entity_id: script.raffstores_up_not_schlafzimmer

- alias: alle up um 21
  trigger:
    platform: time
    at: input_datetime.raffstores_up_2
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.schlafzimmer
        position: 0