- alias: biotonne_notification
  trigger:
    - platform: state
      entity_id: calendar.biotonne
      from: 'off'
      to: 'on'
  action:
    - service: notify.ki_adi_mundi_group
      data:
        message: '🥦 Bitte stell die Biotonne raus! Morgen wird sie abgeholt'
- alias: mistkuebel_notification
  trigger:
    - platform: state
      entity_id: calendar.mistkuebel
      from: 'off'
      to: 'on'
  action:
    - service: notify.ki_adi_mundi_group
      data:
        message: '🗑️ Bitte stell den Mistkübel raus! Heute zu Mittag wird er abgeholt'
- alias: gelber_sack_notification
  trigger:
    - platform: state
      entity_id: calendar.gelber_sack
      from: 'off'
      to: 'on'
  action:
    - service: notify.ki_adi_mundi_group
      data:
        message: '♳ Bitte häng den gelben Sack raus! Morgen wird er abgeholt'