# Enables the frontend
frontend:
# auto discover new devices
discovery:
# show hassio config
hassio:
# Enables configuration UI
config:
# Checks for available updates
updater:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# track the sun
sun:
# z-wave panel and config
zwave:
  usb_path: /dev/ttyACM0

# import folders
automation: !include_dir_merge_list automation/
input_boolean: !include_dir_merge_named input_boolean/
script: !include_dir_merge_named script/

# import files
group: !include group.yaml
homeassistant: !include homeassistant.yaml
input_select: !include input_select.yaml
light: !include light.yaml
switch: !include switch.yaml
