homeassistant: !include homeassistant.yaml

# Enables the frontend
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html

panel_custom: !include panel_custom.yaml

# Enables configuration UI
config:

# necessary for frontend
http:

# Checks for available updates
updater:

# auto discover new devices
discovery:

# Enables support for tracking state changes over time.
recorder:
history:

# View all events in a logbook
logbook:

# show hassio config
hassio:

# track the sun
sun:
# z-wave panel and config
zwave:
  usb_path: /dev/ttyACM0

logger:
  default: debug

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret mi_gateway_key

# import folders
automation: !include_dir_merge_list automation/
input_boolean: !include_dir_merge_named input_boolean/
script: !include_dir_merge_named script/

# import files
group: !include group.yaml
input_select: !include input_select.yaml
light: !include light.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
telegram_bot: !include telegram_bot.yaml
weather: !include weather.yaml
device_tracker: !include device_tracker.yaml
homekit: !include homekit.yaml
