- platform: yeelight
  devices:
    !secret yeelight_sofa_ip:
      name: Sofastripe
    !secret yeelight_bett_ip:
      name: Bettstripe
    !secret yeelight_bedside_ip:
      name: Nachttischlicht Wendelin
    !secret yeelight_bulb_livingroom_ip:
      name: Sofalicht
