- platform: template
  sensors:
    solar_angle:
      value_template: '{{ states.input_select.tv_source.state }}'
      friendly_name: 'TV input source'

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
