- platform: template
  sensors:
    tv_source:
      value_template: '{{ states.input_select.tv_source.state }}'
      friendly_name: 'TV input source'

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: dnsip

- platform: zamg
  monitored_conditions:
    - temperature
    - humidity
    - precipitation
