title: Ki Adi Mundi
views:
  - title: Wohnzimmer
    id: livingroom
    theme: dark-mode
    cards:
      - id: livingroom_lampe
        type: picture-entity
        image: /local/lovelace/livingroom/off.jpg
        state_image:
          off: /local/lovelace/livingroom/off.jpg
          on: /local/lovelace/livingroom/on.jpg
        entity: light.sofalicht
        tap_action: toggle
      - id: livingroom_stripe
        type: picture-entity
        image: /local/lovelace/stripe/off.jpg
        state_image:
          off: /local/lovelace/stripe/off.jpg
          on: /local/lovelace/stripe/on.jpg
        entity: light.sofastripe
      - id: livingroom_fernseher
        type: picture-glance
        state_image:
          off: /local/lovelace/fernseher/off.jpg
          on: /local/lovelace/fernseher/on.jpg
        entity: switch.fernseher
        entities:
          - icon: mdi:power-plug
            entity: switch.fernseher
          - icon: mdi:arrow-expand-left
            entity: script.turn_tv_source_left
          - icon: mdi:arrow-expand-right
            entity: script.turn_tv_source_right
          - icon: mdi:arrow-up-drop-circle-outline
            entity: script.send_tv_simpli_tv_channel_up
          - icon: mdi:arrow-down-drop-circle-outline
            entity: script.send_tv_simpli_tv_channel_down
          - icon: mdi:television-box
            entity: script.send_tv_simpli_tv_channel_on_off
          - icon: mdi:volume-high
            entity: script.tv_audio_on_off
          - icon: mdi:television
            entity: script.tv_samsung_on_off