esphome:
  name: aussen_girlande_terrasse
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_outdoor
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aussen Girlande Terrasse"
    password: "kwURaqiNU83n"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Device Specific Config
output:                                
  - platform: gpio                     
    pin: GPIO4                         
    id: shelly_1_relay                         
                                       
light:                                 
  - platform: binary                   
    name: "Terassen-Girlande Süd"              
    output: shelly_1_relay                     
    id: lightid                        
                                       
binary_sensor:                         
  - platform: gpio                     
    pin:                               
      number: GPIO5           
    on_press:                          
      then:                            
        - light.toggle: lightid        
    internal: true                     
    id: switchid  