esphome:
  name: steckdose_trockner
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Steckdose Trockner"
    password: "Xg8MnSc6cSYX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    id: steckdose_trockner_power_button
    pin:
      number: GPIO3
      inverted: True
    on_press:
      - homeassistant.event:
          event: esphome.steckdose_trockner_button_pressed

switch:
  - platform: gpio
    id: steckdose_trockner_led
    pin:
      number: GPIO1
      inverted: true
  - platform: gpio
    id: steckdose_trockner_relay
    pin: GPIO14
    restore_mode: ALWAYS_ON
  - platform: template
    name: "Steckdose Trockner LED"
    optimistic: yes
    id: led_template
    turn_on_action:
    - while:
        condition:
          lambda: 'return true;'
        then:
        - switch.turn_on: steckdose_trockner_led
        - delay: 500ms 
        - switch.turn_off: steckdose_trockner_led
        - delay: 500ms
    turn_off_action:
    - switch.turn_off: steckdose_trockner_led

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      name: "Steckdose Trockner Ampere"
      unit_of_measurement: A
    voltage:
      name: "Steckdose Trockner Volt"
      unit_of_measurement: V
    power:
      name: "Steckdose Trockner Watt"
      unit_of_measurement: W
      id: "energy_temp_Wattage"
    change_mode_every: 8
    update_interval: 10s