- alias: load toothbrushes battery at night
  trigger:
    platform: time
    at: '04:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_badezimmer_steckdose

- alias: stop loading toothbrushes battery at night
  trigger:
    platform: time
    at: '06:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.switch_badezimmer_steckdose

- alias: load toothbrushes battery at day
  trigger:
    platform: time
    at: '20:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_badezimmer_steckdose

- alias: stop loading toothbrushes battery at day
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.switch_badezimmer_steckdose

- alias: send reminder to close the bathroom window
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002906d10
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Das Badezimmerfenster ist bereits seit 10 Minuten geöffnet. Bitte schließt es!'

- alias: send reminder to close the bathroom window 2
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002906d10
    from: 'off'
    to: 'on'
    for:
      minutes: 15
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Das Badezimmerfenster ist bereits seit 15 Minuten geöffnet. Bitte schließt es!'

- alias: send reminder to close the bathroom window 3
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002906d10
    from: 'off'
    to: 'on'
    for:
      minutes: 30
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Jetzt ist es aber genug! Das Badezimmerfenster ist bereits seit 30 Minuten geöffnet. Bitte schließt es sofort!'
