- alias: load toothbrushes battery at night
  trigger:
    platform: time
    at: '04:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_badezimmer_steckdose

- alias: stop loading toothbrushes battery at night
  trigger:
    platform: time
    at: '06:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.switch_badezimmer_steckdose

- alias: load toothbrushes battery at day
  trigger:
    platform: time
    at: '20:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.switch_badezimmer_steckdose

- alias: stop loading toothbrushes battery at day
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.switch_badezimmer_steckdose
