- alias: turn on codys battery station
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00027bb4bc
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d00026eaf08

- alias: notify that cody is back home
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00027bb4bc
    from: 'on'
    to: 'off'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        title: '*Cody is home*'
        message: 'Commander Cody hat sein Chargingdock erreicht und wird jetzt für 2 Stunden mit Energie gespeist'
    - service: switch.turn_on
      entity_id: switch.plug_158d00026eaf08

- alias: turn off codys battery station
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00027bb4bc
    from: 'on'
    to: 'off'
    for:
      hours: 2
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d00026eaf08