- alias: Wish a good morning and send current conditions
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        title: '*Guten Morgen Caro und Wendi!*'
        message: 'Innentemperatur: *{{ states.sensor.aeotec_multisensor_temperatur_innen.state }} °C*, Luftfeuchtigkeit: *{{ states.sensor.aeotec_multisensor_luftfeutigkeit_innen.state }} %*'
        data:
          inline_keyboard:
            - 'Danke:/danke'

- alias: Status message
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/status'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Innentemperatur: *{{ states.sensor.aeotec_multisensor_temperatur_innen.state }} °C*, Luftfeuchtigkeit: *{{ states.sensor.aeotec_multisensor_luftfeutigkeit_innen.state }} %*'
        data:
          inline_keyboard:
            - /danke

- alias: Status message callback
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/status'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Innentemperatur: *{{ states.sensor.aeotec_multisensor_temperatur_innen.state }} °C*, Luftfeuchtigkeit: *{{ states.sensor.aeotec_multisensor_luftfeutigkeit_innen.state }} %*'
        data:
          inline_keyboard:
            - /danke

- alias: Thank you message
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/danke'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Das mache ich doch gerne. Ich wünsche dir einen schönen Tag. Dein Ki-Adi-Mundi'

- alias: Thank you message callback
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/danke'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'Das mache ich doch gerne. Ich wünsche dir einen schönen Tag. Dein Ki-Adi-Mundi'

- alias: Start message
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
    - service: notify.CARO_WENDI_GROUP
      data:
        title: '*Hallo,*'
        message: 'Ich bin Ki-Adi-Mundi. Du kannst mich immer zum aktuellen Status deiner Wohnung fragen indem du /status sendest oder auf den button unten drückst'
        data:
          inline_keyboard:
            - /status
            - /danke
    - service: notify.CARO_WENDI_GROUP
      data:
        message: 'test'
        data:
          document:
            url: http://i.imgur.com/glrC6qd.gif

- alias: Startup message
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.WENDELIN
      data:
        message: 'Ki-Adi-Mundi meldet sich zum Dienst!'

- alias: Shutdown message
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.WENDELIN
      data:
        message: 'Ich gehe jetzt schlafen. Dein Ki-Adi-Mundi'
