- alias: cube turn off sofastripe and sleep mode on
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000278d378
      action_type: tap_twice
  action:
    - service: light.turn_off
      entity_id: light.sofastripe
    - service: script.schlafen_gehen
    
- alias: cube toggle sofastripe
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000278d378
      action_type: shake_air
  action:
    - service: light.toggle
      entity_id: light.sofastripe