- alias: remote_all_tv_devices_off_from_HDMI_2
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 7
      scene_data: 7680
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 2'
  action:
    - service: script.turn_tv_to_hdmi1_and_off
- alias: remote_all_tv_devices_off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 7
      scene_data: 7680
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 1'
  action:
    - service: script.turn_tv_off

- alias: remote_tv_source_left
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 8
      scene_data: 7680
  action:
    - service: script.turn_tv_source_left

- alias: remote_tv_source_right
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 9
      scene_data: 7680
  action:
    - service: script.turn_tv_source_right

- alias: remote_simpli_tv_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 10
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_on_off

- alias: remote_audio_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 11
      scene_data: 7680
  action:
    - service: script.tv_audio_on_off

- alias: remote_samsung_tv_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 12
      scene_data: 7680
  action:
    - service: script.tv_samsung_on_off

- alias: remote_turn_tv_on_all
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 2
      scene_data: 7800
  action:
    - service: script.turn_tv_on

- alias: remote_tv_channel_down
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 3
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_down

- alias: remote_tv_channel_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 4
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_up

- alias: remote_volume_down
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 5
      scene_data: 7680
  action:
    - service: script.tv_volume_down

- alias: remote_volume_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 6
      scene_data: 7680
  action:
    - service: script.tv_volume_up
