- alias: remote_all_tv_devices_off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 7
      scene_data: 7680
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.tv
    - service: input_boolean.turn_off
      entity_id: input_boolean.tv

- alias: remote_tv_source_left
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 8
      scene_data: 7680
  action:
    - service: script.turn_tv_source_left

- alias: remote_tv_source_right
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 9
      scene_data: 7680
  action:
    - service: script.turn_tv_source_right

- alias: remote_simpli_tv_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 10
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_on_off

- alias: remote_audio_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 11
      scene_data: 7680
  action:
    - service: script.tv_audio_on_off

- alias: remote_samsung_tv_toggle
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 12
      scene_data: 7680
  action:
    - service: script.tv_samsung_on_off

- alias: remote_turn_tv_on_all
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 2
      scene_data: 7800
  action:
    - service: script.turn_tv_on

- alias: remote_tv_channel_down
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 3
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_down

- alias: remote_tv_channel_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 4
      scene_data: 7680
  action:
    - service: script.send_tv_simpli_tv_channel_up

- alias: remote_volume_down
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 5
      scene_data: 7680
  action:
    - service: script.tv_volume_down

- alias: remote_volume_down_long_press
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 5
      scene_data: 7800
  action:
    - service: script.tv_volume_down_3
    - service: input_boolean.turn_on
      entity_id: input_boolean.tv_volume_down_interval_running
    - service: script.start_tv_volume_down_interval

- alias: remote_volume_down_long_press_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 5
      scene_data: 7740
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.tv_volume_down_interval_running

- alias: remote_volume_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 6
      scene_data: 7680
  action:
    - service: script.tv_volume_up

- alias: remote_volume_up_long_press
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 6
      scene_data: 7800
  action:
    - service: script.tv_volume_up_3
    - service: input_boolean.turn_on
      entity_id: input_boolean.tv_volume_up_interval_running
    - service: script.start_tv_volume_up_interval

- alias: remote_volume_up_long_press_up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
      scene_id: 6
      scene_data: 7740
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.tv_volume_up_interval_running
