- alias: turn_tv_on
  trigger:
    - platform: state
      entity_id: switch.fernseher
      to: 'on'
  action:
    - service: script.turn_tv_on

- alias: turn_tv_on_direct
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.fernseher
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.fernseher

- alias: turn_tv_off_hdmi1
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'off'
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 1'
  action:
    - service: script.turn_tv_off

- alias: turn_tv_off_hdmi2
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'off'
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 2'
  action:
    - service: script.turn_tv_to_hdmi1_and_off

- alias: turn_sofastripe_on_tv_on_when_dark
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: state
    entity_id: switch.fernseher
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.sofastripe

- alias: turn_sofastripe_on_tv_on_when_dark2
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  condition:
    condition: state
    entity_id: switch.fernseher
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.sofastripe

- alias: turn_sofastripe_on_tv_on_when_dark3
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: switch.fernseher
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.sofastripe

- alias: turn_sofastripe_on_tv_on_when_dark4
  trigger:
    - platform: state
      entity_id: switch.fernseher
      to: 'on'
  condition:
    condition: state
    entity_id: sun
    state: 'below horizon'
  action:
    service: light.turn_on
    entity_id: light.sofastripe

- alias: turn_sofastripe_off_tv_off_when_dark
  trigger:
    platform: switch.fernseher
    event: state_changed
    entity_id: switch.fernseher
    new_state: 'off'
    offset: "+00:15:00"
  condition:
    condition: state
    entity_id: light.sofastripe
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.sofastripe
