- alias: turn_tv_on
  trigger:
    - platform: state
      entity_id: switch.unnamed_device
      to: 'on'
  action:
    - service: script.turn_tv_on

- alias: turn_tv_on_direct
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.unnamed_device
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.unnamed_device

- alias: turn_tv_off_hdmi1
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'off'
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 1'
  action:
    - service: script.turn_tv_off

- alias: turn_tv_off_hdmi2
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'off'
  condition:
    - condition: state
      entity_id: input_select.tv_source
      state: 'HDMI 2'
  action:
    - service: script.turn_tv_to_hdmi1_and_off
